// GENERATED by scripts/dev/gen-content-en.mjs — do not hand-edit.
//
// English reference copy for curated landmark and nature records. The
// corresponding .fr and .ar modules must expose exactly the same slugs and
// fields; tests/content.test.mjs enforces that, and scripts/check-content.mjs
// fails the build if they drift.
//
// src/data/{landmarks,nature}.ts hold the structural facts (slugs, codes,
// coordinates, list membership). This module holds only user-visible prose.

export type LandmarkCopy = {
  name: string
  type: string
  built: string
  height?: string
  period: string
  description: string
  bestTime?: string
  facts: string[]
}

export type NatureCopy = {
  name: string
  type: string
  area?: string
  established?: string
  description: string
  climate: string
  bestTime: string
  wildlife: string[]
  activities: string[]
  facts: string[]
}

export type LandmarkCopyDict = Record<string, LandmarkCopy>
export type NatureCopyDict = Record<string, NatureCopy>

export const landmarksEn: LandmarkCopyDict = {
  "everest": {
    "name": "Mount Everest",
    "type": "Mountain",
    "built": "Natural formation",
    "height": "8,848.86 m",
    "period": "Formed over millions of years",
    "description": "Mount Everest is Earth’s highest peak above sea level, rising from the Himalayas on the border of Nepal and China. It is the ultimate mountaineering challenge and a sacred landscape for local Sherpa communities.",
    "bestTime": "April to May, and September to October",
    "facts": [
      "Its height was most recently measured at 8,848.86 metres in 2020.",
      "The first confirmed ascent was by Edmund Hillary and Tenzing Norgay in 1953.",
      "The summit sits on the border between Nepal and Tibet.",
      "The mountain is known as Sagarmatha in Nepali and Chomolungma in Tibetan."
    ]
  },
  "machu-picchu": {
    "name": "Machu Picchu",
    "type": "Ancient city",
    "built": "c. 1450 CE",
    "height": "2,430 m above sea level",
    "period": "Inca Empire",
    "description": "Machu Picchu is a 15th-century Inca citadel perched on a mountain ridge above the Sacred Valley. Its dry-stone walls, terraces and temples showcase remarkable Inca engineering.",
    "bestTime": "May to September (dry season)",
    "facts": [
      "It was built at the height of the Inca Empire for the emperor Pachacuti.",
      "The site was never discovered by Spanish conquistadors.",
      "It was brought to international attention by Hiram Bingham in 1911.",
      "The stonework uses no mortar, with blocks fitted so tightly that a blade can barely pass between them."
    ]
  },
  "great-wall": {
    "name": "Great Wall of China",
    "type": "Fortification",
    "built": "7th century BCE onward",
    "height": "Up to 8 m",
    "period": "Multiple dynasties",
    "description": "The Great Wall is a vast network of fortifications stretching thousands of kilometres across northern China. Sections were built and rebuilt over many dynasties to defend against invasions.",
    "bestTime": "April to May and September to October",
    "facts": [
      "It is not a single wall but many interconnected walls and branches.",
      "The most famous sections near Beijing were built during the Ming dynasty.",
      "Estimates of its total length exceed 21,000 kilometres.",
      "Watchtowers allowed soldiers to signal warnings with smoke and fire."
    ]
  },
  "petra": {
    "name": "Petra",
    "type": "Rock-cut architecture",
    "built": "c. 312 BCE",
    "height": "Al-Khazneh facade about 39 m",
    "period": "Nabataean Kingdom",
    "description": "Petra is an ancient city carved directly into rose-red sandstone cliffs. Once the capital of the Nabataeans, it was a thriving trading hub on routes between Arabia and the Mediterranean.",
    "bestTime": "March to May and September to November",
    "facts": [
      "Its buildings are carved into rock rather than constructed.",
      "The Treasury, or Al-Khazneh, is its most iconic facade.",
      "An ingenious system of channels supplied the desert city with water.",
      "It was largely forgotten by the West until the 19th century."
    ]
  },
  "taj-mahal": {
    "name": "Taj Mahal",
    "type": "Mausoleum",
    "built": "1632–1653 CE",
    "height": "73 m",
    "period": "Mughal Empire",
    "description": "The Taj Mahal is a white marble mausoleum built by Emperor Shah Jahan in memory of his wife Mumtaz Mahal. Its symmetry, gardens and inlaid stonework make it a masterpiece of Mughal architecture.",
    "bestTime": "October to March",
    "facts": [
      "It took roughly 20,000 artisans and over 20 years to complete.",
      "The marble changes appearance with the shifting light of day.",
      "It is flanked by a mosque and a guest house for symmetry.",
      "Semi-precious stones are inlaid into the marble in floral patterns."
    ]
  },
  "colosseum": {
    "name": "Colosseum",
    "type": "Amphitheatre",
    "built": "70–80 CE",
    "height": "48 m",
    "period": "Roman Empire",
    "description": "The Colosseum is the largest amphitheatre ever built, an engineering marvel of ancient Rome where gladiatorial contests and public spectacles were staged for crowds of tens of thousands.",
    "bestTime": "April to June and September to October",
    "facts": [
      "It could hold an estimated 50,000 to 80,000 spectators.",
      "A retractable awning called the velarium shaded the audience.",
      "Underground passages, known as the hypogeum, housed gladiators and animals.",
      "It remained in use for around 500 years."
    ]
  },
  "pyramids": {
    "name": "Pyramids of Giza",
    "type": "Monument",
    "built": "c. 2560 BCE",
    "height": "Great Pyramid originally 146.6 m",
    "period": "Ancient Egypt",
    "description": "The Pyramids of Giza are among the oldest surviving wonders of the ancient world. The Great Pyramid was built as a tomb for the pharaoh Khufu and remains a symbol of Egyptian civilisation.",
    "bestTime": "October to April",
    "facts": [
      "The Great Pyramid was the tallest human-made structure for over 3,800 years.",
      "The nearby Great Sphinx is carved from a single limestone outcrop.",
      "Millions of stone blocks were moved and fitted with astonishing precision.",
      "They are aligned closely with the cardinal directions."
    ]
  },
  "christ-redeemer": {
    "name": "Christ the Redeemer",
    "type": "Statue",
    "built": "1922–1931 CE",
    "height": "30 m, 38 m with pedestal",
    "period": "Modern era",
    "description": "Christ the Redeemer is an Art Deco statue of Jesus Christ overlooking Rio de Janeiro from the peak of Corcovado mountain. It has become an iconic symbol of Brazil and of welcome.",
    "bestTime": "May to October",
    "facts": [
      "It is made of reinforced concrete and covered in soapstone tiles.",
      "The arms stretch about 28 metres wide.",
      "It sits 710 metres above the city.",
      "It is illuminated at night and frequently struck by lightning."
    ]
  },
  "angkor-wat": {
    "name": "Angkor Wat",
    "type": "Temple complex",
    "built": "c. 1113–1150 CE",
    "height": "Central tower about 65 m",
    "period": "Khmer Empire",
    "description": "Angkor Wat is the largest religious monument in the world, built by King Suryavarman II as a Hindu temple and later used as a Buddhist site. Its galleries are covered in intricate bas-reliefs.",
    "bestTime": "November to March",
    "facts": [
      "It is the largest religious structure on Earth by land area.",
      "It appears on the national flag of Cambodia.",
      "The temple is oriented to the west, unlike most Khmer temples.",
      "Its moat and walls helped protect it from the jungle over centuries."
    ]
  },
  "stonehenge": {
    "name": "Stonehenge",
    "type": "Prehistoric monument",
    "built": "c. 3000–2000 BCE",
    "height": "Tallest stones about 7 m",
    "period": "Neolithic and Bronze Age",
    "description": "Stonehenge is a prehistoric circle of massive standing stones on Salisbury Plain. Its exact purpose remains debated, but it was clearly aligned with the movements of the sun.",
    "bestTime": "May to September",
    "facts": [
      "The largest sarsen stones weigh around 25 tonnes each.",
      "Some smaller bluestones were transported from Wales.",
      "The monument is aligned with the summer and winter solstices.",
      "It was built and altered over roughly 1,500 years."
    ]
  },
  "acropolis": {
    "name": "Acropolis of Athens",
    "type": "Citadel",
    "built": "5th century BCE",
    "height": "156 m above sea level",
    "period": "Classical Greece",
    "description": "The Acropolis is a rocky citadel above Athens crowned by the Parthenon. It represents the high point of classical Greek architecture, art and democracy.",
    "bestTime": "April to June and September to October",
    "facts": [
      "The Parthenon was dedicated to the goddess Athena.",
      "It was built in just under a decade in the 5th century BCE.",
      "The buildings use subtle optical refinements instead of perfectly straight lines.",
      "It has served as a temple, church, mosque and fortress over its history."
    ]
  },
  "chichen-itza": {
    "name": "Chichén Itzá",
    "type": "Archaeological site",
    "built": "c. 600–1200 CE",
    "height": "El Castillo about 30 m",
    "period": "Maya civilisation",
    "description": "Chichén Itzá is a large Maya city notable for the pyramid of El Castillo, the Great Ball Court and the sacred cenote. It blends Maya and Toltec architectural styles.",
    "bestTime": "November to March",
    "facts": [
      "El Castillo has 365 steps, matching the days of the solar year.",
      "At the equinoxes, shadow creates the appearance of a serpent descending.",
      "Its Great Ball Court is the largest in Mesoamerica.",
      "The site takes its name from a sacred sinkhole, or cenote."
    ]
  },
  "hanging-gardens-of-babylon": {
    "name": "Hanging Gardens of Babylon",
    "type": "Terraced garden complex",
    "built": "Attributed to Nebuchadnezzar II, 6th century BCE",
    "period": "Neo-Babylonian Empire",
    "description": "The Hanging Gardens of Babylon are described by Greek writers as a series of irrigated terraces planted with trees and rising in stepped levels above the city. No archaeological trace of them has been found, and leading historians continue to dispute whether they existed at all.",
    "facts": [
      "They are attributed to King Nebuchadnezzar II, who reigned from 605 to 562 BCE.",
      "The account comes from later Greek writers, including Diodorus Siculus and Strabo, not Babylonian records.",
      "No remains have been identified; the proposed location near Babylon in modern Iraq remains unconfirmed.",
      "Some scholars argue the description may derive from a different structure or be a later literary invention."
    ]
  },
  "statue-of-zeus": {
    "name": "Statue of Zeus at Olympia",
    "type": "Colossal cult statue",
    "built": "c. 435 BCE",
    "height": "Reportedly about 12 m (40 ft)",
    "period": "Classical Greece",
    "description": "The Statue of Zeus at Olympia was a chryselephantine figure of the god seated in a throne, made by the sculptor Phidias inside the Temple of Zeus. It was one of the most celebrated works of ancient sculpture and is known chiefly through the description of the travel writer Pausanias.",
    "facts": [
      "It was made by Phidias, who also sculpted the Athena Parthenos at Athens.",
      "It was built from gold and ivory over a wooden core.",
      "Pausanias described it in his second-century CE account of Greece.",
      "The original was destroyed by fire at Olympia in 476 CE; a Roman-era replacement statue stood in its place."
    ]
  },
  "temple-of-artemis": {
    "name": "Temple of Artemis at Ephesus",
    "type": "Temple",
    "built": "Original c. 550 BCE; rebuilt in the Hellenistic period",
    "height": "Reportedly about 115 m (377 ft) including the columns",
    "period": "Archaic Greek to Hellenistic",
    "description": "The Temple of Artemis at Ephesus, near Selçuk in modern Türkiye, was a vast sanctuary to the goddess Artemis that was rebuilt several times and destroyed in antiquity. Its excavated foundations remain one of the most important ancient sanctuaries in the region.",
    "facts": [
      "It was dedicated to Artemis and served as one of the major cult centres of the ancient Mediterranean.",
      "The temple was rebuilt after an arson in 356 BCE, reputedly on the same night Alexander the Great was born.",
      "It was destroyed in the early 5th century CE; later accounts dispute the cause.",
      "The site itself is today part of the UNESCO-listed ancient city of Ephesus, about 3 km away."
    ]
  },
  "mausoleum-at-halicarnassus": {
    "name": "Mausoleum at Halicarnassus",
    "type": "Tomb monument",
    "built": "c. 353–350 BCE",
    "height": "Reportedly about 45 m (148 ft)",
    "period": "Classical Greek / early Hellenistic",
    "description": "The Mausoleum at Halicarnassus was the tomb of King Mausolus, built by his widow Artemisia II in the 4th century BCE. It gave its name to the word mausoleum, and a reconstruction survives in the remains kept inside the Castle of St Peter in Bodrum.",
    "facts": [
      "It was built for Mausolus, satrap of Caria, and completed by his widow and sister Artemisia II.",
      "The name \"mausoleum\" derives from this building.",
      "Sculptors including Scopas and Praxiteles are associated with its decoration.",
      "It was damaged by earthquakes and dismantled in the medieval period; surviving fragments are displayed in Bodrum."
    ]
  },
  "colossus-of-rhodes": {
    "name": "Colossus of Rhodes",
    "type": "Colossal bronze statue",
    "built": "c. 292–280 BCE",
    "height": "Reportedly about 33 m (108 ft)",
    "period": "Hellenistic",
    "description": "The Colossus of Rhodes was a bronze statue of the sun god Helios, erected at the entrance to the harbour of Rhodes by the sculptor Chares of Lindos. It stood only a few decades before being toppled by an earthquake, and was later dismantled.",
    "facts": [
      "It was built by Chares of Lindos, who was a pupil of Lysippos.",
      "Accounts describe it as standing at the harbour entrance beside the famous statues at the mole.",
      "It was knocked down by an earthquake in the 2nd century BCE, commonly dated to 226 BCE.",
      "It was removed in the 2nd century CE, probably by the Romans; the site is now the Mandraki harbour area."
    ]
  },
  "lighthouse-of-alexandria": {
    "name": "Lighthouse of Alexandria",
    "type": "Lighthouse",
    "built": "c. 280 BCE",
    "height": "Estimated roughly 100 m (about 328 ft) in its final phase",
    "period": "Ptolemaic Egypt",
    "description": "The Lighthouse of Alexandria, or Pharos, was a tiered tower built on the island of Pharos off the Egyptian coast under Ptolemy II. Guided by the architect Sostratus, it stood in three diminishing sections and served ships for many centuries before collapsing.",
    "facts": [
      "It was built during the reign of Ptolemy II Philadelphus, generally dated to about 280 BCE.",
      "It stood on the island of Pharos, which gave the island and the lighthouse its name.",
      "A Roman-era lighthouse stood there after the original fell, and it was destroyed in the medieval period.",
      "The fortress of the Qaitbay Citadel, built in the 15th century, stands on part of the site."
    ]
  }
}

export const natureEn: NatureCopyDict = {
  "amazon": {
    "name": "Amazon Rainforest",
    "type": "Tropical rainforest",
    "area": "About 5,500,000 km²",
    "established": "Ancient, protected in parts since the 20th century",
    "description": "The Amazon is the largest tropical rainforest on Earth, spanning nine countries and drained by the mighty Amazon River. It is one of the most biodiverse places on the planet and a vital carbon sink.",
    "climate": "Hot and humid year-round, with a pronounced wet season",
    "bestTime": "June to November (lower water, more trails)",
    "wildlife": [
      "Jaguar",
      "Pink river dolphin",
      "Harpy eagle",
      "Poison dart frog",
      "Sloth",
      "Howler monkey"
    ],
    "activities": [
      "River cruises",
      "Jungle trekking",
      "Wildlife spotting",
      "Canoeing",
      "Visiting local communities"
    ],
    "facts": [
      "It produces a significant share of the world’s oxygen and freshwater.",
      "The Amazon River discharges more water than any other river on Earth.",
      "Millions of species live here, many still undocumented.",
      "Deforestation is a major threat to its ecosystems."
    ]
  },
  "grand-canyon": {
    "name": "Grand Canyon",
    "type": "Canyon",
    "area": "4,927 km² national park",
    "established": "National park in 1919",
    "description": "The Grand Canyon is a mile-deep chasm carved by the Colorado River through layered red rock. Its immense scale and exposed geology tell a story spanning nearly two billion years.",
    "climate": "Semi-arid; cooler on the rims, much hotter on the canyon floor",
    "bestTime": "March to May and September to November",
    "wildlife": [
      "California condor",
      "Bighorn sheep",
      "Mule deer",
      "Raven",
      "Kaibab squirrel"
    ],
    "activities": [
      "Rim hiking",
      "Whitewater rafting",
      "Scenic drives",
      "Stargazing",
      "Mule rides"
    ],
    "facts": [
      "The canyon is about 446 kilometres long.",
      "Its average depth is roughly 1.6 kilometres.",
      "The Colorado River continues to shape it today.",
      "It is one of the Seven Natural Wonders of the World."
    ]
  },
  "niagara-falls": {
    "name": "Niagara Falls",
    "type": "Waterfall",
    "area": "Three waterfalls on the Niagara River",
    "established": "Protected as a reserve in 1885",
    "description": "Niagara Falls is a group of three powerful waterfalls on the border of Canada and the United States. Horseshoe Falls is the largest and most famous, drawing millions of visitors each year.",
    "climate": "Continental, with cold winters and warm summers",
    "bestTime": "June to August, and December for the Festival of Lights",
    "wildlife": [
      "Gulls",
      "Cormorants",
      "Sturgeon",
      "Beaver",
      "White-tailed deer"
    ],
    "activities": [
      "Boat tours",
      "Cave of the Winds",
      "Observation decks",
      "Nightly illumination",
      "Hornblower cruises"
    ],
    "facts": [
      "Around 2,800 cubic metres of water flow over the falls every second.",
      "The falls have retreated several kilometres over thousands of years.",
      "Hydroelectric stations divert water for power generation.",
      "The Canadian Horseshoe Falls is the widest of the three."
    ]
  },
  "serengeti": {
    "name": "Serengeti National Park",
    "type": "Savanna",
    "area": "14,750 km²",
    "established": "National park in 1951",
    "description": "The Serengeti is a vast savanna ecosystem famed for the Great Migration, when millions of wildebeest and zebra move in search of greener pastures. It hosts one of the greatest concentrations of wildlife on Earth.",
    "climate": "Tropical savanna, with a long dry season and short rains",
    "bestTime": "June to October (dry season and river crossings)",
    "wildlife": [
      "Wildebeest",
      "Zebra",
      "Lion",
      "Cheetah",
      "Leopard",
      "Elephant",
      "Black rhinoceros"
    ],
    "activities": [
      "Game drives",
      "Hot-air balloon safaris",
      "Migration viewing",
      "Birdwatching",
      "Cultural visits"
    ],
    "facts": [
      "The Great Migration involves around 1.5 million wildebeest.",
      "It is part of the larger Serengeti-Mara ecosystem.",
      "The park is a UNESCO World Heritage Site.",
      "Predators gather along the Grumeti and Mara rivers during crossings."
    ]
  },
  "galapagos": {
    "name": "Galápagos Islands",
    "type": "Volcanic archipelago",
    "area": "About 8,010 km²",
    "established": "National park in 1959",
    "description": "The Galápagos Islands are a volcanic archipelago in the Pacific whose unique species helped inspire Charles Darwin’s theory of evolution. Its wildlife is famously fearless of humans.",
    "climate": "Subtropical, with a cool dry season and a warm wet season",
    "bestTime": "June to November (cooler) and December to May (warmer)",
    "wildlife": [
      "Giant tortoise",
      "Marine iguana",
      "Blue-footed booby",
      "Galápagos penguin",
      "Sea lion",
      "Waved albatross"
    ],
    "activities": [
      "Snorkelling",
      "Diving",
      "Wildlife watching",
      "Hiking",
      "Island hopping"
    ],
    "facts": [
      "The islands sit on a volcanic hotspot.",
      "Darwin visited in 1835 aboard HMS Beagle.",
      "Many species are found nowhere else on Earth.",
      "Strict visitor rules help protect the fragile ecosystem."
    ]
  },
  "great-barrier-reef": {
    "name": "Great Barrier Reef",
    "type": "Coral reef",
    "area": "About 344,400 km²",
    "established": "Marine park in 1975",
    "description": "The Great Barrier Reef is the world’s largest coral reef system, a labyrinth of thousands of reefs and islands off the coast of Queensland. It teems with marine life and is visible from space.",
    "climate": "Tropical, warm year-round",
    "bestTime": "June to October (dry season, clear water)",
    "wildlife": [
      "Clownfish",
      "Green sea turtle",
      "Reef shark",
      "Humpback whale",
      "Giant clam",
      "Manta ray"
    ],
    "activities": [
      "Diving",
      "Snorkelling",
      "Glass-bottom boat tours",
      "Sailing",
      "Helicopter flights"
    ],
    "facts": [
      "It is composed of around 2,900 individual reefs.",
      "It supports an extraordinary diversity of marine species.",
      "Coral bleaching linked to warming seas is a major concern.",
      "It is a UNESCO World Heritage Site."
    ]
  },
  "yellowstone": {
    "name": "Yellowstone National Park",
    "type": "Volcanic plateau and wilderness",
    "area": "8,991 km²",
    "established": "World’s first national park, 1872",
    "description": "Yellowstone sits atop a vast volcanic hotspot and contains more than half of the world’s geysers. Its geothermal features, canyons and wildlife make it a landmark of conservation.",
    "climate": "Continental, with short cool summers and long cold winters",
    "bestTime": "June to September",
    "wildlife": [
      "Gray wolf",
      "Bison",
      "Grizzly bear",
      "Elk",
      "Bald eagle",
      "Trumpeter swan"
    ],
    "activities": [
      "Geyser watching",
      "Wildlife viewing",
      "Hiking",
      "Camping",
      "Cross-country skiing"
    ],
    "facts": [
      "Old Faithful erupts on a fairly predictable schedule.",
      "The park sits on a dormant supervolcano.",
      "It was the first national park in the world.",
      "Wolves were reintroduced in 1995 after decades of absence."
    ]
  },
  "banff": {
    "name": "Banff National Park",
    "type": "Mountain park",
    "area": "6,641 km²",
    "established": "Canada’s first national park, 1885",
    "description": "Banff is Canada’s oldest national park, set in the Rocky Mountains around turquoise glacial lakes, rugged peaks and hot springs. It is a year-round destination for outdoor adventure.",
    "climate": "Subarctic to alpine, with long snowy winters",
    "bestTime": "June to August, and December to March for snow sports",
    "wildlife": [
      "Grizzly bear",
      "Bighorn sheep",
      "Moose",
      "Elk",
      "Wolf",
      "Golden eagle"
    ],
    "activities": [
      "Hiking",
      "Skiing",
      "Canoeing",
      "Scenic drives",
      "Wildlife watching"
    ],
    "facts": [
      "Lake Louise is famous for its vivid turquoise colour.",
      "The park is part of the Canadian Rocky Mountain Parks World Heritage Site.",
      "The Icefields Parkway links Banff with Jasper.",
      "Hot springs in the park helped inspire its creation."
    ]
  },
  "patagonia": {
    "name": "Patagonia",
    "type": "Region of mountains, steppe and ice fields",
    "area": "About 1,043,000 km²",
    "established": "Protected across many national parks",
    "description": "Patagonia is a vast region at the southern tip of South America shared by Argentina and Chile. It is known for dramatic granite peaks, glaciers, windswept steppe and pristine wilderness.",
    "climate": "Cool and windy, with frequent weather changes",
    "bestTime": "November to March (southern summer)",
    "wildlife": [
      "Guanaco",
      "Andean condor",
      "Magellanic penguin",
      "Puma",
      "Southern right whale",
      "Huemul deer"
    ],
    "activities": [
      "Trekking",
      "Glacier walking",
      "Kayaking",
      "Wildlife watching",
      "Scenic flights"
    ],
    "facts": [
      "The region includes the Southern Patagonian Ice Field.",
      "Mount Fitz Roy and Torres del Paine are iconic peaks.",
      "The Perito Moreno Glacier is one of the few that advances.",
      "Its name comes from the word used by Magellan for local inhabitants."
    ]
  },
  "yosemite": {
    "name": "Yosemite National Park",
    "type": "Glacial valley and park",
    "area": "3,027 km²",
    "established": "National park in 1890",
    "description": "Yosemite is celebrated for its towering granite cliffs, giant sequoias and spectacular waterfalls. Its glacier-carved valley is one of the most recognisable landscapes in North America.",
    "climate": "Mediterranean to alpine, with snowy winters and dry summers",
    "bestTime": "May to September",
    "wildlife": [
      "American black bear",
      "Mule deer",
      "Bobcat",
      "Peregrine falcon",
      "Mountain chickadee",
      "Sierra Nevada bighorn sheep"
    ],
    "activities": [
      "Hiking",
      "Rock climbing",
      "Scenic drives",
      "Photography",
      "Camping"
    ],
    "facts": [
      "El Capitan is a granite monolith about 900 metres tall.",
      "Yosemite Falls is among the tallest waterfalls in North America.",
      "Giant sequoias here can live for over 3,000 years.",
      "The park helped inspire the modern conservation movement."
    ]
  },
  "victoria-falls": {
    "name": "Victoria Falls",
    "type": "Waterfall",
    "area": "About 1,088 m wide and 108 m high at the main falls",
    "established": "Mosi-oa-Tunya National Park since 2019",
    "description": "Victoria Falls is a broad curtain of water on the Zambezi River at the border of Zambia and Zimbabwe. Its local name, Mosi-oa-Tunya, is usually translated as “the smoke that thunders”.",
    "climate": "Tropical savanna, with the main rains from November to March",
    "bestTime": "May to September, when the falls are at their widest",
    "wildlife": [
      "African elephant",
      "Cape buffalo",
      "Lion",
      "White rhinoceros",
      "Giraffe",
      "Pygmy hippo"
    ],
    "activities": [
      "Canoeing the upper Zambezi",
      "Rafting below the falls",
      "Bungee jumping",
      "Game viewing",
      "Sunset walks"
    ],
    "facts": [
      "It is roughly twice as wide as Niagara Falls, though not as high.",
      "The local name Mosi-oa-Tunya is usually translated as “the smoke that thunders”.",
      "The falls sit in a basalt gorge left by ancient lava flows.",
      "Its spray can be heard before the falls themselves come into view."
    ]
  },
  "iguazu-falls": {
    "name": "Iguazú Falls",
    "type": "Waterfall",
    "area": "About 2,700 m of waterfall along the Argentina–Brazil border",
    "established": "National park since 1902; UNESCO since 1986",
    "description": "Iguazú Falls is a long series of cataracts on the Iguazú River on the border of Argentina and Brazil. In Guaraní, “iguazú” is usually translated as “big water”.",
    "climate": "Subtropical and humid, with rain throughout the year",
    "bestTime": "April to June and September to November",
    "wildlife": [
      "Jaguar",
      "Black caiman",
      "Giant anteater",
      "Howler monkey",
      "Capybara",
      "Helmeted woodpecker"
    ],
    "activities": [
      "Upper and lower circuit trails",
      "Train to the falls",
      "Boat rides",
      "Wildlife watching",
      "Birding"
    ],
    "facts": [
      "The Devil’s Throat is the largest single drop in the system.",
      "The name is commonly translated from Guaraní as “big water”.",
      "Many plants and animals around the falls occur nowhere else on Earth.",
      "The falls can be visited from either the Argentine or the Brazilian side."
    ]
  },
  "lake-baikal": {
    "name": "Lake Baikal",
    "type": "Freshwater lake",
    "area": "About 31,722 km²",
    "established": "UNESCO World Heritage Site since 1998",
    "description": "Lake Baikal in southern Siberia is the deepest lake on Earth and holds roughly a fifth of the world’s unfrozen fresh water. Large parts of its bed lie well below the surrounding land, in a rift basin.",
    "climate": "Continental extreme, with very severe winters and deep ice",
    "bestTime": "June to September; ice caves in winter",
    "wildlife": [
      "Baikal seal",
      "Baikal omul",
      "Baikal gray wolf",
      "Red deer",
      "Buryat crane"
    ],
    "activities": [
      "Winter ice caves",
      "Boat and hydrofoil trips",
      "Shoreline hiking",
      "Seal observation",
      "Spring ice photography"
    ],
    "facts": [
      "It reaches a depth of about 1,642 metres.",
      "It is the largest freshwater lake by volume in the world.",
      "Around 80% of its animal life is found nowhere else.",
      "Its winter ice can reach about a metre thick."
    ]
  },
  "halong-bay": {
    "name": "Hạ Long Bay",
    "type": "Bay of limestone karst islands",
    "area": "About 1,553 km²",
    "established": "UNESCO World Heritage Site since 1994",
    "description": "Hạ Long Bay is a UNESCO World Heritage Site in northern Vietnam, famous for the thousands of limestone islands and islets that rise from the sea. Its name is usually translated as “descending dragon bay”.",
    "climate": "Monsoonal, with wet summers and cooler, drier winters",
    "bestTime": "October to December and March to May",
    "wildlife": [
      "Whale shark",
      "Catfish",
      "Dolphin",
      "Asian black bear",
      "Oriental white stork"
    ],
    "activities": [
      "Overnight boat cruises",
      "Kayaking",
      "Cave visits",
      "Fishing villages",
      "Bird watching"
    ],
    "facts": [
      "The bay contains more than 1,600 islands, islets and rock outcrops.",
      "Its karst towers formed over hundreds of millions of years.",
      "It is also written Ha Long Bay in international usage.",
      "Fishing has shaped the bay’s communities for centuries."
    ]
  },
  "angel-falls": {
    "name": "Angel Falls",
    "type": "Waterfall",
    "area": "979 m total drop; the longest uninterrupted descent",
    "established": "Part of Canaima National Park, a UNESCO site since 2009",
    "description": "Angel Falls is a waterfall in Canaima National Park, Venezuela, falling from the Auyán-tepui plateau. It is widely described as the world’s highest uninterrupted waterfall. The Pemón name Kerepakupai Merú is usually translated as “the deepest place on Earth”.",
    "climate": "Tropical and wet all year, with a rainier season",
    "bestTime": "June to December",
    "wildlife": [
      "Spectacled bear",
      "Orinoco crocodile",
      "Harpy eagle",
      "Golden lion tamarin"
    ],
    "activities": [
      "Airstrip landings on the tepui",
      "River travel on the Caroní",
      "Canoeing",
      "Bird watching",
      "Guided hikes"
    ],
    "facts": [
      "It drops 979 m in total, with an unbroken run of roughly 807 m.",
      "It is named after aviator Jimmie Angel, who flew over it in 1933.",
      "Its base is so remote that it can take days to reach by river.",
      "The surrounding tepuis are among the oldest exposed rock formations on Earth."
    ]
  },
  "sahara": {
    "name": "Sahara Desert",
    "type": "Hot desert",
    "area": "About 9,200,000 km²",
    "established": "Protected areas established across the region",
    "description": "The Sahara is the largest hot desert in the world, covering much of North Africa. Despite its reputation, a great deal of its surface is rocky desert rather than sand, and it has been far greener during earlier humid periods.",
    "climate": "Hot desert, with very large differences between day and night",
    "bestTime": "October to March, for cooler weather",
    "wildlife": [
      "Fennec fox",
      "Addax",
      "Dromedary camel",
      "Saharan cheetah",
      "Scimitar oryx"
    ],
    "activities": [
      "Dune trekking",
      "Oasis visits",
      "Rock art sites",
      "Night sky observing",
      "Camel journeys"
    ],
    "facts": [
      "Its area is roughly comparable to that of the United States.",
      "The largest dune fields lie in the south, in the Erg Chebbi and Erg Murzuk regions.",
      "It has repeatedly been far greener during the African humid periods.",
      "It is the largest hot desert, unlike the much colder Antarctic desert."
    ]
  }
}
